// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type City struct {
	ID        string  `json:"id"`
	Countryid float64 `json:"countryid"`
	Cityname  string  `json:"cityname"`
}

type Country struct {
	ID          string `json:"id"`
	Countryname string `json:"countryname"`
}

type Degree struct {
	ID         string `json:"id"`
	Degreename string `json:"degreename"`
}

type DeleteTemporary struct {
	URL string `json:"url"`
}

type Education struct {
	ID             string   `json:"id"`
	Schoolid       float64  `json:"schoolid"`
	Degreeid       float64  `json:"degreeid"`
	Fieldofstudyid float64  `json:"fieldofstudyid"`
	Startdate      string   `json:"startdate"`
	Enddate        *string  `json:"enddate"`
	Grade          *float64 `json:"grade"`
	Activities     *string  `json:"activities"`
	Description    *string  `json:"description"`
}

type Employmenttype struct {
	ID                 string `json:"id"`
	Employmenttypename string `json:"employmenttypename"`
}

type Experience struct {
	ID               string  `json:"id"`
	Userid           float64 `json:"userid"`
	Title            string  `json:"title"`
	Employmenttypeid float64 `json:"employmenttypeid"`
	Industryid       float64 `json:"industryid"`
	Companyname      string  `json:"companyname"`
	Location         string  `json:"location"`
	Startdate        string  `json:"startdate"`
	Enddate          *string `json:"enddate"`
	Description      *string `json:"description"`
}

type Experienceskill struct {
	ID           string  `json:"id"`
	Skillid      float64 `json:"skillid"`
	Experienceid float64 `json:"experienceid"`
}

type Industry struct {
	ID           string `json:"id"`
	Industryname string `json:"industryname"`
}

type Job struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Company  string  `json:"company"`
	Location string  `json:"location"`
	Userid   float64 `json:"userid"`
}

type Location struct {
	ID        string  `json:"id"`
	Countryid float64 `json:"countryid"`
	Cityid    float64 `json:"cityid"`
}

type Mediatype struct {
	ID            string `json:"id"`
	Mediatypename string `json:"mediatypename"`
}

type NewJob struct {
	Name     string  `json:"name"`
	Company  string  `json:"company"`
	Location string  `json:"location"`
	Userid   float64 `json:"userid"`
}

type NewPass struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

type NewTemporary struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	URL      string `json:"url"`
}

type NewUser struct {
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Password   string `json:"password"`
	Profileurl string `json:"profileurl"`
	Email      string `json:"email"`
	Activation bool   `json:"activation"`
}

type Phonetype struct {
	ID            string `json:"id"`
	Phonetypename string `json:"phonetypename"`
}

type Pronoun struct {
	ID           string `json:"id"`
	Pronounsname string `json:"pronounsname"`
}

type School struct {
	ID         string `json:"id"`
	Schoolname string `json:"schoolname"`
}

type Servicetype struct {
	ID          string `json:"id"`
	Servicename string `json:"servicename"`
}

type Skill struct {
	ID        string `json:"id"`
	Skillname string `json:"skillname"`
}

type Studyfield struct {
	ID        string `json:"id"`
	Fieldname string `json:"fieldname"`
}

type Temporary struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	URL      string `json:"url"`
}

type User struct {
	ID             string   `json:"id"`
	Pronounsid     *float64 `json:"pronounsid"`
	Firstname      string   `json:"firstname"`
	Lastname       string   `json:"lastname"`
	Additionalname *string  `json:"additionalname"`
	Headline       string   `json:"headline"`
	Locationid     *float64 `json:"locationid"`
	Usercontactsid *float64 `json:"usercontactsid"`
	Password       string   `json:"password"`
	Profile        *string  `json:"profile"`
	Banner         *string  `json:"banner"`
	Profileurl     string   `json:"profileurl"`
	Email          string   `json:"email"`
	Activation     bool     `json:"activation"`
	About          string   `json:"about"`
}

type Userconnection struct {
	ID            string  `json:"id"`
	Userid        float64 `json:"userid"`
	Useridconnect float64 `json:"useridconnect"`
	Status        bool    `json:"status"`
}

type Usercontact struct {
	ID                string   `json:"id"`
	Userphonenumberid *float64 `json:"userphonenumberid"`
	Address           *string  `json:"address"`
	Birthday          *string  `json:"birthday"`
}

type Usercurrposition struct {
	ID           string `json:"id"`
	Experienceid string `json:"experienceid"`
}

type Usereducation struct {
	ID          string  `json:"id"`
	Userid      float64 `json:"userid"`
	Educationid float64 `json:"educationid"`
}

type Userfollower struct {
	ID             string  `json:"id"`
	Userid         float64 `json:"userid"`
	Useridfollower float64 `json:"useridfollower"`
}

type Userfollowing struct {
	ID             string  `json:"id"`
	Userid         float64 `json:"userid"`
	Useridfollowed float64 `json:"useridfollowed"`
}

type Userinstantmessaging struct {
	ID            string  `json:"id"`
	Usercontactid float64 `json:"usercontactid"`
	Serviceid     float64 `json:"serviceid"`
	Username      string  `json:"username"`
}

type Userphonenumber struct {
	ID          string  `json:"id"`
	Phonenumber string  `json:"phonenumber"`
	Phonetypeid float64 `json:"phonetypeid"`
}

type Userwebsite struct {
	ID             string  `json:"id"`
	Usercontactsid float64 `json:"usercontactsid"`
	Websitetypeid  float64 `json:"websitetypeid"`
	Websiteurl     string  `json:"websiteurl"`
}

type Websitetype struct {
	ID              string `json:"id"`
	Websitetypename string `json:"websitetypename"`
}
