// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type City struct {
	ID        string  `json:"id"`
	Countryid float64 `json:"countryid"`
	Cityname  string  `json:"cityname"`
}

type Comment struct {
	ID      string  `json:"id"`
	Userid  float64 `json:"userid"`
	Postid  float64 `json:"postid"`
	Comment string  `json:"comment"`
}

type Commentlike struct {
	ID        string  `json:"id"`
	Commentid float64 `json:"commentid"`
	Userid    float64 `json:"userid"`
}

type Commentreply struct {
	ID           string  `json:"id"`
	Commentid    float64 `json:"commentid"`
	Userid       float64 `json:"userid"`
	Commentreply string  `json:"commentreply"`
}

type Commentreplylike struct {
	ID             string  `json:"id"`
	Userid         float64 `json:"userid"`
	Commentreplyid float64 `json:"commentreplyid"`
}

type Country struct {
	ID          string `json:"id"`
	Countryname string `json:"countryname"`
}

type Degree struct {
	ID         string `json:"id"`
	Degreename string `json:"degreename"`
}

type DelConnect struct {
	Userid        float64 `json:"userid"`
	Useridconnect float64 `json:"useridconnect"`
}

type DeleteTemporary struct {
	URL string `json:"url"`
}

type EditProfile struct {
	ID        string  `json:"id"`
	Firstname string  `json:"firstname"`
	Lastname  string  `json:"lastname"`
	Headline  *string `json:"headline"`
	About     *string `json:"about"`
	Profile   *string `json:"profile"`
	Banner    *string `json:"banner"`
}

type Education struct {
	ID           string   `json:"id"`
	Grade        *float64 `json:"grade"`
	Activities   *string  `json:"activities"`
	Description  *string  `json:"description"`
	Schoolname   string   `json:"schoolname"`
	Degreeid     float64  `json:"degreeid"`
	Fieldofstudy string   `json:"fieldofstudy"`
	Startdate    string   `json:"startdate"`
	Enddate      *string  `json:"enddate"`
	Userid       float64  `json:"userid"`
}

type Employmenttype struct {
	ID                 string `json:"id"`
	Employmenttypename string `json:"employmenttypename"`
}

type Experience struct {
	ID              string  `json:"id"`
	Userid          float64 `json:"userid"`
	Title           string  `json:"title"`
	Employmentypeid float64 `json:"employmentypeid"`
	Companyname     string  `json:"companyname"`
	Location        string  `json:"location"`
	Startdate       string  `json:"startdate"`
	Enddate         *string `json:"enddate"`
	Description     *string `json:"description"`
	Industry        string  `json:"industry"`
}

type Industry struct {
	ID           string `json:"id"`
	Industryname string `json:"industryname"`
}

type Job struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Company  string  `json:"company"`
	Location string  `json:"location"`
	Userid   float64 `json:"userid"`
}

type Like struct {
	ID     string  `json:"id"`
	Userid float64 `json:"userid"`
	Postid float64 `json:"postid"`
}

type Location struct {
	ID        string  `json:"id"`
	Countryid float64 `json:"countryid"`
	Cityid    float64 `json:"cityid"`
}

type NewComment struct {
	Userid  float64 `json:"userid"`
	Postid  float64 `json:"postid"`
	Comment *string `json:"comment"`
}

type NewCommentLike struct {
	Commentid float64 `json:"commentid"`
	Userid    float64 `json:"userid"`
}

type NewCommentReply struct {
	Commentid    float64 `json:"commentid"`
	Userid       float64 `json:"userid"`
	Commentreply string  `json:"commentreply"`
}

type NewCommentReplyLike struct {
	Userid         float64 `json:"userid"`
	Commentreplyid float64 `json:"commentreplyid"`
}

type NewConnect struct {
	Userid        float64 `json:"userid"`
	Useridconnect float64 `json:"useridconnect"`
	Status        bool    `json:"status"`
}

type NewEducation struct {
	Grade        *float64 `json:"grade"`
	Activities   *string  `json:"activities"`
	Description  *string  `json:"description"`
	Schoolname   string   `json:"schoolname"`
	Degreeid     float64  `json:"degreeid"`
	Fieldofstudy string   `json:"fieldofstudy"`
	Startdate    string   `json:"startdate"`
	Enddate      *string  `json:"enddate"`
	Userid       float64  `json:"userid"`
}

type NewExperience struct {
	Userid          float64 `json:"userid"`
	Title           string  `json:"title"`
	Employmentypeid float64 `json:"employmentypeid"`
	Companyname     string  `json:"companyname"`
	Location        string  `json:"location"`
	Startdate       string  `json:"startdate"`
	Enddate         *string `json:"enddate"`
	Description     *string `json:"description"`
	Industry        string  `json:"industry"`
}

type NewFollower struct {
	Userid         float64 `json:"userid"`
	Useridfollower float64 `json:"useridfollower"`
}

type NewFollowing struct {
	Userid         float64 `json:"userid"`
	Useridfollowed float64 `json:"useridfollowed"`
}

type NewJob struct {
	Name     string  `json:"name"`
	Company  string  `json:"company"`
	Location string  `json:"location"`
	Userid   float64 `json:"userid"`
}

type NewLike struct {
	Userid float64 `json:"userid"`
	Postid float64 `json:"postid"`
}

type NewNotification struct {
	Userid float64 `json:"userid"`
	Desc   string  `json:"desc"`
	Date   string  `json:"date"`
}

type NewPass struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

type NewPost struct {
	Userid  float64 `json:"userid"`
	Media   *string `json:"media"`
	Caption string  `json:"caption"`
	Display string  `json:"display"`
}

type NewTemporary struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	URL      string `json:"url"`
}

type NewUser struct {
	Firstname  string  `json:"firstname"`
	Lastname   string  `json:"lastname"`
	Password   string  `json:"password"`
	Profileurl string  `json:"profileurl"`
	Email      string  `json:"email"`
	Activation bool    `json:"activation"`
	Theme      float64 `json:"theme"`
	Display    string  `json:"display"`
}

type NewUserBlock struct {
	Userid        float64 `json:"userid"`
	Useridblocked float64 `json:"useridblocked"`
}

type NewView struct {
	Useridviewed float64 `json:"useridviewed"`
}

type Notification struct {
	ID     string  `json:"id"`
	Userid float64 `json:"userid"`
	Desc   string  `json:"desc"`
	Date   string  `json:"date"`
}

type Post struct {
	ID      string  `json:"id"`
	Userid  float64 `json:"userid"`
	Media   *string `json:"media"`
	Caption string  `json:"caption"`
	Display *string `json:"display"`
}

type Profileview struct {
	ID           string  `json:"id"`
	Useridviewed float64 `json:"useridviewed"`
	Deletestatus bool    `json:"deletestatus"`
}

type Pronoun struct {
	ID           string `json:"id"`
	Pronounsname string `json:"pronounsname"`
}

type School struct {
	ID         string `json:"id"`
	Schoolname string `json:"schoolname"`
}

type Studyfield struct {
	ID        string `json:"id"`
	Fieldname string `json:"fieldname"`
}

type Temporary struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	URL      string `json:"url"`
}

type UpdateConnect struct {
	Userid        float64 `json:"userid"`
	Useridconnect float64 `json:"useridconnect"`
	Status        bool    `json:"status"`
}

type UpdateTheme struct {
	ID    string  `json:"id"`
	Theme float64 `json:"theme"`
}

type User struct {
	ID             string   `json:"id"`
	Pronounsid     *float64 `json:"pronounsid"`
	Firstname      string   `json:"firstname"`
	Lastname       string   `json:"lastname"`
	Additionalname *string  `json:"additionalname"`
	Headline       string   `json:"headline"`
	Password       string   `json:"password"`
	Profile        *string  `json:"profile"`
	Banner         *string  `json:"banner"`
	Profileurl     string   `json:"profileurl"`
	Email          string   `json:"email"`
	Activation     bool     `json:"activation"`
	About          string   `json:"about"`
	Locationid     *float64 `json:"locationid"`
	Theme          float64  `json:"theme"`
	Display        *string  `json:"display"`
}

type Userblock struct {
	ID            string  `json:"id"`
	Userid        float64 `json:"userid"`
	Useridblocked float64 `json:"useridblocked"`
}

type Userconnection struct {
	ID            string  `json:"id"`
	Userid        float64 `json:"userid"`
	Useridconnect float64 `json:"useridconnect"`
	Status        bool    `json:"status"`
}

type Userfollower struct {
	ID             string  `json:"id"`
	Userid         float64 `json:"userid"`
	Useridfollower float64 `json:"useridfollower"`
}

type Userfollowing struct {
	ID             string  `json:"id"`
	Userid         float64 `json:"userid"`
	Useridfollowed float64 `json:"useridfollowed"`
}
